swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: User Bank Accounts
      description: API for fetching user bank accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User bank accounts retrieved successfully
          schema:
            $ref: '#/definitions/BankAccounts'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /accounts/{id}:
    get:
      security:
        - BearerAuth: []
      tags:
        - Accounts Module
      summary: Get a specific bank account
      description: API for retrieving a specific bank account by ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          description: The bank account ID
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User bank account retrieved successfully
          schema:
            $ref: '#/definitions/BankAccounts'
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
  /accounts/{id}/transactions:
    get:
      security:
        - BearerAuth: []
      tags:
        - Transactions Module
      summary: Get transactions for a specific account
      description: API for retrieving transactions of a specific account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          description: The bank account ID to retrieve transactions for
          type: string
          required: true
        - in: query
          name: page
          description: Page number to retrieve
          type: integer
          format: int32
          default: 1
          required: false
        - in: query
          name: pageSize
          description: Number of items per page
          type: integer
          format: int32
          default: 10
          required: false
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/Transactions'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
  /transactions/{id}:
    put:
      security:
        - BearerAuth: []
      tags:
        - Transactions Module
      summary: Update transaction details
      description: API for updating the category and notes of a specific transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          description: The transaction ID to update
          type: string
          required: true
        - in: body
          name: body
          description: Update transaction category and notes
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
              notes:
                type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details updated successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  BankAccounts:
    type: object
    properties:
      id:
        type: string
        description: bank account ID
      name:
        type: string
        description: bank account name
      balance:
        type: number
        description: bank account balance
      type:
        type: string
        description: bank account type
  Transactions:
    type: object
    properties:
      id:
        type: string
        description: transaction ID
      accountId:
        type: string
        description: bank account ID
      amount:
        type: number
        description: transaction amount
      date:
        type: string
        description: transaction date and time
      balanceAtTransaction:
        type: number
        description: account balance at the time of the transaction
      type:
        type: string
        description: transaction type
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: user notes about the transaction
